---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-bedrock
  labels:
    role: service-config
    app: minecraft
data:
  # Find more options at https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
  # Remove # from in front of line if changing from default values.
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  GAMEMODE: "survival" # Options: survival, creative, adventure
  DIFFICULTY: "normal" # Options: peaceful, easy, normal, hard
  #DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
  LEVEL_NAME: "Home_minecraft_world"
  LEVEL_SEED: "6933480944"
  SERVER_NAME: "Home_minecraft_server"
  #SERVER_PORT: "19132"
  LEVEL_TYPE: "DEFAULT" # Options: FLAT, LEGACY, DEFAULT
  ALLOW_CHEATS: "false" # Options: true, false
  #MAX_PLAYERS: "10"
  #PLAYER_IDLE_TIMEOUT: "30"
  #TEXTUREPACK_REQUIRED: "false" # Options: true, false
  #
  ## Changing these will have a security impact
  #ONLINE_MODE: "true" # Options: true, false (removes Xbox Live account requirements)
  #WHITE_LIST: "false" # If enabled, need to provide a whitelist.json by your own means. 
  #
  ## Changing these will have a performance impact
  #VIEW_DISTANCE: "10"
  #TICK_DISTANCE: "4"
  #MAX_THREADS: "8"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minecraft
  name: minecraft
spec:
  # never more than 1 since BDS is not horizontally scalable
  replicas: 1
  serviceName: minecraft
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: main
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-bedrock
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /etc/timezone
              name: timezonefile
            - mountPath: /etc/localtime
              name: localtimefile
          ports:
            - containerPort: 19132
              protocol: UDP
          readinessProbe: &probe
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                # force health check against IPv4 port
                - 127.0.0.1
            initialDelaySeconds: 30
          livenessProbe: *probe
      volumes:
      - name: data
        hostPath:
            path: /sharedpath/storagelocation/minecraft/data
            type: Directory
      - name: timezonefile
        hostPath:
            path: /etc/timezone
            type: File
      - name: localtimefile
        hostPath:
            path: /etc/localtime
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: minecraft
  ports:
    - port: 19132
      protocol: UDP
#  ipFamily: IPv4
  # Use LoadBalancer if running on a provider that supports that
#  type: LoadBalancer
  # or use NodePort on a non-managed system;
  # however, you'll need to lookup port assigned to the service
  type: LoadBalancer

